### ISSUE TITLE
error running with name regex

### ISSUE THREAD

**Issue by tcskill** [cloud-native-toolkit/automation-solutions#86] opened 2022-04-20 02:07 UTC
running on existing cluster, gives this error during apply for each node:

Error: "name" ("3-pwx-kube-c9fj1nnw0d0i0q7og6d0-masdev2-default-00000c0c") should match regexp ^([a-z]|[a-z][-a-z0-9]*[a-z0-9])$
│
│  with module.ibm-portworx.ibm_is_volume.volume[3],
│  on .terraform/modules/ibm-portworx/main.tf line 67, in resource "ibm_is_volume" "volume":
│  67:  name      = substr("${replace(var.name_prefix, "_", "-")}${length(var.name_prefix) > 0 ? "-" : ""}${count.index}-pwx-${var.workers[count.index].id}", 0, 61) [#max](https://ibm-analytics.slack.com/archives/C588U3MFT) length of 61 characters for volume name

**Comment by triceam** [comment] 2022-04-21 15:42
Closing, duplicate of https://github.com/cloud-native-toolkit/software-everywhere/issues/146, which has more info

**Closed by triceam** 2022-04-21 15:42 UTC
Labels: bug
